version: '3.0'
services:
    eventDB:
        image: postgres
        environment:
            - POSTGRES_USER=${EVENT_DB_USERNAME}
            - POSTGRES_PASSWORD=${EVENT_DB_PASSWORD}
            - POSTGRES_DB=${EVENT_DB_NAME}
        ports:
            - '${EVENT_DB_PORT}:5432'

            