export const enum EventTypeErrorCode {
  EVENT_TYPE_TABLE_EXISTS = 'EVENT_TYPE_TABLE_EXISTS',
  EVENT_TYPE_TABLE_DOES_NOT_EXIST = 'EVENT_TYPE_TABLE_DOESNT_EXIST',
  EVENT_TYPE_WITH_NAME_ALREADY_EXISTS = 'EVENT_TYPE_WITH_NAME_ALREADY_EXISTS',
  UNEXPECTED_PG_ERROR = 'UNEXPECTED_PG_ERROR',
}
